service: aws-python-scheduled-cron

frameworkVersion: '2'

provider:
  name: aws
  runtime: python3.8
  lambdaHashingVersion: 20201221

functions:
  rateHandler:
    handler: wootric.run
    events:
      # Invoke Lambda function every hour
      - schedule: rate(1 hour)

useDotenv: true

plugins:
  - serverless-python-requirements
